import { StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";
import { availableTargets, setupDefaults, type Target } from "./targets";
import {
  generateOwnerCode,
  ownerCodeReady,
  type OwnerCodeMode,
} from "./owner-code";

type Operation =
  | "install"
  | "update"
  | "repair"
  | "rollback"
  | "backup"
  | "restore"
  | "export"
  | "uninstall";
type ProductChannel = "preview" | "release-candidate" | "stable";
type SSHAuthMethod = "agent" | "private-key" | "password";
type ThemeMode = "auto" | "light" | "dark";
type Phase = {
  name: string;
  state: "waiting" | "running" | "passed" | "failed";
  detail?: string;
};

type ReleaseIdentity = {
  version: string;
  channel: ProductChannel;
  manifestUrl: string;
  manifestSha256: string;
};

type OperationSummary = {
  planId: string;
  operation: Operation;
  target: string;
  mode: string;
  status: string;
  startedAt: string;
  finishedAt?: string;
};

type ScoutUpdateStatus = {
  updateAvailable: boolean;
  currentVersion: string;
  latestVersion?: string;
  releaseUrl?: string;
  assetName?: string;
  assetSha256?: string;
};

type WindowsConnectionProfile = {
  schemaVersion: 1;
  profileId: string;
  displayName: string;
  mode: "connected";
  clientKind: "windows";
  backendUrl: string;
  deploymentProfile: "cloudflare" | "compose";
  provisioningSource: "scout";
  createdAt: string;
  compatibility: {
    productVersion: string;
    apiContract: string;
    syncContract: number;
    databaseMigration: string;
  };
};

const cloudflareAllowances = [
  ["Workers", "100,000 dynamic requests each day"],
  [
    "D1 records",
    "5 million rows read and 100,000 rows written each day; 5 GB stored",
  ],
  [
    "R2 photos",
    "10 GB-month stored; 1 million Class A and 10 million Class B operations each month",
  ],
] as const;

const wizardSteps = [
  "Choose a setup",
  "Details",
  "Review",
  "Install & verify",
  "Finish",
] as const;

const railNotes: Record<number, string> = {
  1: "Scout runs only while this window is open. It never installs anything in the background.",
  2: "Scout runs only while this window is open. It never installs anything in the background.",
  3: "Nothing is downloaded or installed until you review this summary and choose to apply it.",
  4: "If any check fails, Scout stops before installing and nothing on the target changes.",
  5: "Come back to Scout anytime — to update, back up, restore, or repair.",
};

const token = location.hash.slice(1);
// Owner UAT finding (2026-07-19): a lost loopback backend must never surface
// as a raw fetch error. Every Scout API call is loopback-only, so a network
// failure means Scout's own local process is gone.
const localServiceLost =
  "Scout's local service stopped — close this tab and relaunch Scout Bee.";
const call = async <T,>(path: string, init?: RequestInit): Promise<T> => {
  let response: Response;
  try {
    response = await fetch(path, {
      ...init,
      headers: {
        authorization: `Bearer ${token}`,
        "content-type": "application/json",
        ...init?.headers,
      },
    });
  } catch {
    throw new Error(localServiceLost);
  }
  const body = (await response.json().catch(() => ({}))) as {
    message?: string;
  };
  if (!response.ok)
    throw new Error(
      body.message ?? `Scout Bee could not continue (${response.status})`,
    );
  return body as T;
};

function BeeMark() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" aria-hidden="true">
      <circle cx="10" cy="11" r="5.5" fill="var(--accent)" />
      <rect x="5" y="9" width="10" height="1.8" fill="var(--rail)" />
      <rect x="5.6" y="12" width="8.8" height="1.8" fill="var(--rail)" />
      <ellipse
        cx="6.5"
        cy="5.5"
        rx="3.4"
        ry="2.2"
        fill="#ffffff"
        opacity=".85"
      />
      <ellipse
        cx="13.5"
        cy="5.5"
        rx="3.4"
        ry="2.2"
        fill="#ffffff"
        opacity=".85"
      />
    </svg>
  );
}

function App() {
  const [target, setTarget] = useState<Target>("cloudflare");
  const [operation, setOperation] = useState<Operation>("install");
  const [productChannel, setProductChannel] =
    useState<ProductChannel>("stable");
  const [cloudflareToken, setCloudflareToken] = useState("");
  // Owner decision (2026-07-19): the one-time owner setup code is
  // auto-generated by default; bootstrapToken holds the advanced custom code.
  const [ownerCodeMode, setOwnerCodeMode] = useState<OwnerCodeMode>("auto");
  const [generatedOwnerCode, setGeneratedOwnerCode] = useState(() =>
    generateOwnerCode(),
  );
  const [ownerCodeSaved, setOwnerCodeSaved] = useState(false);
  const [ownerCodeCopied, setOwnerCodeCopied] = useState(false);
  const [bootstrapToken, setBootstrapToken] = useState("");
  const [sshAuthMethod, setSSHAuthMethod] = useState<SSHAuthMethod>("agent");
  const [sshPrivateKeyPath, setSSHPrivateKeyPath] = useState("");
  const [sshPrivateKeyPassphrase, setSSHPrivateKeyPassphrase] = useState("");
  const [sshPassword, setSSHPassword] = useState("");
  const [includeWebFrontend, setIncludeWebFrontend] = useState(true);
  const [keepData, setKeepData] = useState(true);
  const [costAcknowledged, setCostAcknowledged] = useState(false);
  const [restoreAcknowledged, setRestoreAcknowledged] = useState(false);
  const [step, setStep] = useState(1);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [phases, setPhases] = useState<Phase[]>([]);
  const [lastRunMode, setLastRunMode] = useState<
    "" | "dry-run" | "apply" | "resume"
  >("");
  const [release, setRelease] = useState<ReleaseIdentity | null>(null);
  const [stableChannelEmpty, setStableChannelEmpty] = useState(false);
  const [history, setHistory] = useState<OperationSummary[]>([]);
  const [connectionProfile, setConnectionProfile] =
    useState<WindowsConnectionProfile | null>(null);
  // Defaults to off: the Windows client target stays hidden unless the Scout
  // server explicitly reports SCOUT_BEE_ENABLE_WINDOWS_CLIENT (ADR 0023).
  const [windowsClientEnabled, setWindowsClientEnabled] = useState(false);
  const [scoutVersion, setScoutVersion] = useState("");
  // On-open Scout self-update check (ADR 0023: run-on-demand, no auto-update,
  // no background anything). Checked once at launch; fails quietly offline.
  const [scoutUpdate, setScoutUpdate] = useState<ScoutUpdateStatus | null>(
    null,
  );
  const [theme, setTheme] = useState<ThemeMode>("auto");
  const [form, setForm] = useState<Record<string, string>>({
    accountReference: "",
    workerName: "apiarylens-family",
    d1DatabaseName: "apiarylens-family",
    r2BucketName: "apiarylens-family-media",
    customDomain: "",
    backupDestination: "",
    backupFilePath: "",
    windowsArchivePath: "",
    host: "",
    user: "apiarylens",
    targetDirectory: "/opt/apiarylens",
    projectName: "apiarylens-family",
    publicUrl: "https://hives.example.com",
    sshHostKeySha256: "",
    localDirectory: setupDefaults["compose-local"].installDirectory,
    localHttpPort: String(setupDefaults["compose-local"].httpPort),
  });
  // Live writability feedback for the local-trial install folder, checked on
  // blur so a bad folder is corrected on Details instead of failing preflight
  // two steps later (owner UAT 2026-07-19).
  const [localFolderState, setLocalFolderState] = useState<
    "" | "checking" | "writable" | "unwritable"
  >("");
  async function checkLocalFolder() {
    if (!form.localDirectory) return;
    setLocalFolderState("checking");
    try {
      const result = await call<{ checked?: boolean; writable?: boolean }>(
        "/api/v1/local/folder-check",
        {
          method: "POST",
          body: JSON.stringify({ directory: form.localDirectory }),
        },
      );
      setLocalFolderState(
        result.checked !== true
          ? ""
          : result.writable
            ? "writable"
            : "unwritable",
      );
    } catch {
      setLocalFolderState("");
    }
  }
  const plan = useMemo(
    () => ({
      schemaVersion: 1,
      planId: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      release:
        release ??
        ({
          version: "",
          channel: productChannel,
          manifestUrl: "",
          manifestSha256: "",
        } as const),
      operation,
      keepDataOnUninstall: keepData,
      target: target === "plan-only" ? "cloudflare" : target,
      ...(target === "compose-local"
        ? {
            localCompose: {
              installDirectory: form.localDirectory,
              projectName: form.projectName,
              httpPort: Number.parseInt(form.localHttpPort, 10) || 8420,
            },
          }
        : target === "compose-ssh"
          ? {
              compose: {
                host: form.host,
                port: 22,
                user: form.user,
                targetDirectory: form.targetDirectory,
                projectName: form.projectName,
                publicUrl: form.publicUrl,
                sshHostKeySha256: form.sshHostKeySha256,
                backupRetention: 14,
                includeWebFrontend,
              },
            }
          : target === "windows-client"
            ? { windowsClient: { architecture: "x64" } }
            : {
                cloudflare: {
                  accountReference: form.accountReference,
                  workerName: form.workerName,
                  d1DatabaseName: form.d1DatabaseName,
                  r2BucketName: form.r2BucketName,
                  ...(form.customDomain
                    ? { customDomain: form.customDomain }
                    : {}),
                  costProfile: "family-free-guarded",
                  includeWebFrontend,
                },
              }),
    }),
    [
      target,
      form,
      operation,
      keepData,
      release,
      productChannel,
      includeWebFrontend,
    ],
  );
  useEffect(() => {
    setRelease(null);
    setError("");
    setStableChannelEmpty(false);
    const advanced = productChannel === "stable" ? "" : "&advanced=true";
    void fetch(`/api/v1/release?channel=${productChannel}${advanced}`, {
      headers: { authorization: `Bearer ${token}` },
    })
      .then(async (response) => {
        const body = (await response.json().catch(() => ({}))) as {
          message?: string;
          channelEmpty?: boolean;
        } & Partial<ReleaseIdentity>;
        if (response.ok) {
          setRelease(body as ReleaseIdentity);
          return;
        }
        // Owner UAT finding (2026-07-19): while no stable ApiaryLens release
        // exists, say so plainly and guide toward the preview opt-in instead
        // of dead-ending on an error.
        if (productChannel === "stable" && body.channelEmpty === true) {
          setStableChannelEmpty(true);
          return;
        }
        setError(
          body.message ??
            (productChannel === "stable"
              ? "No compatible Stable release is currently available. Preview and RC builds are available only through Advanced release channel opt-in."
              : "The release identity is unavailable"),
        );
      })
      .catch(() => setError(localServiceLost));
  }, [productChannel]);
  async function refreshHistory() {
    const result = await call<{ items: OperationSummary[] }>("/api/v1/history");
    setHistory(result.items);
  }
  useEffect(() => {
    void refreshHistory().catch(() => undefined);
  }, []);
  useEffect(() => {
    void call<{ windowsClientEnabled?: boolean; version?: string }>(
      "/api/v1/status",
    )
      .then((status) => {
        setWindowsClientEnabled(status.windowsClientEnabled === true);
        if (typeof status.version === "string") setScoutVersion(status.version);
      })
      .catch(() => undefined);
  }, []);
  useEffect(() => {
    void call<ScoutUpdateStatus>("/api/v1/scout-update")
      .then((status) =>
        setScoutUpdate(status.updateAvailable === true ? status : null),
      )
      .catch(() => undefined);
  }, []);
  useEffect(() => {
    if (theme === "auto")
      document.documentElement.removeAttribute("data-theme");
    else document.documentElement.setAttribute("data-theme", theme);
  }, [theme]);
  const update = (name: string, value: string) =>
    setForm((current) => ({ ...current, [name]: value }));

  async function run(mode: "dry-run" | "apply" | "resume") {
    setBusy(true);
    setError("");
    setLastRunMode(mode);
    try {
      const result = await call<{
        phases: Phase[];
        connectionProfile?: WindowsConnectionProfile;
      }>("/api/v1/execute", {
        method: "POST",
        body: JSON.stringify({
          plan,
          mode,
          secrets: {
            ...(target === "cloudflare" && cloudflareToken
              ? { cloudflareApiToken: cloudflareToken }
              : {}),
            ...(operation === "install" && effectiveOwnerCode
              ? { bootstrapToken: effectiveOwnerCode }
              : {}),
            ...(target === "compose-ssh"
              ? {
                  sshAuthMethod,
                  ...(sshAuthMethod === "private-key"
                    ? {
                        sshPrivateKeyPath,
                        ...(sshPrivateKeyPassphrase
                          ? { sshPrivateKeyPassphrase }
                          : {}),
                      }
                    : {}),
                  ...(sshAuthMethod === "password" ? { sshPassword } : {}),
                }
              : {}),
            ...(target === "windows-client" &&
            (operation === "backup" || operation === "restore") &&
            form.windowsArchivePath
              ? { windowsArchivePath: form.windowsArchivePath }
              : {}),
            ...(target === "cloudflare" && form.backupDestination
              ? { backupDestination: form.backupDestination }
              : {}),
            ...(target === "cloudflare" && form.backupFilePath
              ? { backupFilePath: form.backupFilePath }
              : {}),
          },
        }),
      });
      setPhases(result.phases);
      setConnectionProfile(result.connectionProfile ?? null);
      await refreshHistory();
      setStep(4);
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "Scout Bee could not continue",
      );
    } finally {
      setBusy(false);
    }
  }
  async function cancel() {
    try {
      await call(`/api/v1/operations/${plan.planId}?action=cancel`, {
        method: "POST",
      });
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "Scout Bee could not cancel safely",
      );
    }
  }
  async function saveDiagnostics() {
    try {
      const diagnostics = await call<Record<string, unknown>>(
        `/api/v1/diagnostics/${plan.planId}`,
      );
      const blob = new Blob([JSON.stringify(diagnostics, null, 2)], {
        type: "application/json",
      });
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = `apiarylens-scout-diagnostics-${plan.planId}.json`;
      a.click();
      URL.revokeObjectURL(a.href);
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "Scout Bee could not create diagnostics",
      );
    }
  }
  function exportPlan() {
    const blob = new Blob([JSON.stringify(plan, null, 2)], {
      type: "application/json",
    });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "apiarylens-deployment.json";
    a.click();
    URL.revokeObjectURL(a.href);
  }
  function saveConnectionProfile() {
    if (!connectionProfile) return;
    const blob = new Blob([JSON.stringify(connectionProfile, null, 2)], {
      type: "application/json",
    });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "apiarylens-windows-connection.json";
    a.click();
    URL.revokeObjectURL(a.href);
  }
  function startBackup() {
    setOperation("backup");
    setRestoreAcknowledged(false);
    setPhases([]);
    setLastRunMode("");
    setStep(2);
  }
  function finishWizard() {
    setPhases([]);
    setLastRunMode("");
    setConnectionProfile(null);
    // The generated owner code was shown once for this install; a new wizard
    // pass gets a fresh one.
    setGeneratedOwnerCode(generateOwnerCode());
    setOwnerCodeSaved(false);
    setOwnerCodeCopied(false);
    setStep(1);
  }
  const lastVerifiedBackup = history.find(
    (item) =>
      item.operation === "backup" &&
      item.mode === "apply" &&
      item.status === "passed",
  );
  const lastRestore = history.find((item) => item.operation === "restore");
  const runFailed = phases.some((phase) => phase.state === "failed");
  // A successful resume completes the interrupted apply (codex P2 finding).
  const applyPassed =
    (lastRunMode === "apply" || lastRunMode === "resume") &&
    phases.length > 0 &&
    !runFailed;
  // Health evidence may only be claimed when a health-verification phase
  // actually passed in this run (codex P2 finding): backup, export, and
  // uninstall never establish it.
  const healthVerified = phases.some(
    (phase) => phase.state === "passed" && /health/i.test(phase.name),
  );
  const lifecycleOperation =
    operation === "install" ||
    operation === "update" ||
    operation === "repair" ||
    operation === "rollback";
  // Owner decision (2026-07-19): auto-generated by default; a local trial
  // never blocks on the code (shown at handoff), exposed backends require a
  // saved-it confirmation, and the advanced custom code validates inline.
  const ownerCodeNeeded =
    operation === "install" &&
    target !== "plan-only" &&
    target !== "windows-client";
  const effectiveOwnerCode = !ownerCodeNeeded
    ? ""
    : ownerCodeMode === "custom"
      ? bootstrapToken
      : generatedOwnerCode;
  const ownerCodeMissing =
    ownerCodeNeeded &&
    !ownerCodeReady(target, ownerCodeMode, bootstrapToken, ownerCodeSaved);
  function copyOwnerCode() {
    void navigator.clipboard
      ?.writeText(effectiveOwnerCode)
      .then(() => setOwnerCodeCopied(true))
      .catch(() => undefined);
  }
  const backendAddress =
    connectionProfile?.backendUrl ??
    (lifecycleOperation
      ? target === "compose-ssh"
        ? form.publicUrl
        : target === "compose-local"
          ? `http://localhost:${Number.parseInt(form.localHttpPort, 10) || 8420}`
          : target === "cloudflare" && form.customDomain
            ? form.customDomain
            : ""
      : "");
  const nextThemeLabel =
    theme === "auto" ? "Auto" : theme === "light" ? "Light" : "Dark";

  return (
    <div className="ground">
      <div className="dialog">
        <div className="titlebar">
          <span className="dot" aria-hidden="true"></span>
          <span>
            Scout Bee{scoutVersion ? ` ${scoutVersion}` : ""} — ApiaryLens{" "}
            {step === 5 ? "handoff" : "setup"}
          </span>
          <button
            className="theme-btn"
            onClick={() =>
              setTheme(
                theme === "auto"
                  ? "light"
                  : theme === "light"
                    ? "dark"
                    : "auto",
              )
            }
          >
            Theme: {nextThemeLabel}
          </button>
        </div>
        <aside className="rail" aria-label="Setup steps">
          <div className="brand">
            <BeeMark />
            Scout Bee
          </div>
          {wizardSteps.map((label, index) => (
            <div
              className={
                "step" +
                (step === index + 1 ? " now" : step > index + 1 ? " done" : "")
              }
              key={label}
            >
              <span className="n">{step > index + 1 ? "✓" : index + 1}</span>
              {label}
            </div>
          ))}
          <div className="rail-note">{railNotes[step]}</div>
        </aside>
        <div className="pane" aria-live={step === 4 ? "polite" : undefined}>
          {error && (
            <div className="error" role="alert">
              {error}
            </div>
          )}
          {step === 1 && (
            <>
              <h1>Where should your family’s hive records live?</h1>
              <p className="lede">
                Pick the setup that fits your family. Every choice installs the
                same ApiaryLens — only where it runs is different, and you can
                see exactly what each one means before anything happens.
              </p>
              {stableChannelEmpty && productChannel === "stable" && (
                <div className="callout stable-empty" role="note">
                  <h3>No stable release yet</h3>
                  <p>
                    ApiaryLens hasn’t shipped a stable release yet — previews
                    are currently the only channel. Preview builds change
                    frequently and aren’t for your family’s only copy of the
                    records. Every download is still verified the same way —
                    SHA-256 checksum and GitHub build attestation — before
                    anything is installed.
                  </p>
                  <div className="act">
                    <button
                      className="btn primary"
                      onClick={() => setProductChannel("preview")}
                    >
                      Use the Preview channel
                    </button>
                  </div>
                </div>
              )}
              <div
                className="choices"
                role="radiogroup"
                aria-label="Setup choices"
              >
                <div
                  className={
                    "choice compound" +
                    (target === "compose-local" || target === "windows-client"
                      ? " selected"
                      : "")
                  }
                >
                  <span className="radio" aria-hidden="true"></span>
                  <h2>
                    On this local machine{" "}
                    <span className="flag">No server needed</span>
                  </h2>
                  <p>
                    Everything stays on this computer at http://localhost —
                    nothing is uploaded anywhere and there is nothing to sign up
                    for. Because this computer holds the only copy, Scout will
                    help you make backup files — they are your safety net.
                  </p>
                  <div className="sub-choices">
                    {availableTargets(windowsClientEnabled)
                      .filter(
                        (definition) =>
                          definition.id === "compose-local" ||
                          definition.id === "windows-client",
                      )
                      .map((definition) => (
                        <button
                          className={
                            "sub-choice" +
                            (target === definition.id ? " selected" : "")
                          }
                          role="radio"
                          aria-checked={target === definition.id}
                          key={definition.id}
                          onClick={() => setTarget(definition.id)}
                        >
                          <span className="radio small" aria-hidden="true" />
                          <b>
                            {definition.title}{" "}
                            <span className="flag">{definition.flag}</span>
                          </b>
                          <p>{definition.description}</p>
                        </button>
                      ))}
                    {!windowsClientEnabled && (
                      <div
                        className="sub-choice placeholder"
                        aria-disabled="true"
                      >
                        <span className="radio small" aria-hidden="true" />
                        <b>
                          Windows app{" "}
                          <span className="flag soon">Coming soon</span>
                        </b>
                        <p>
                          A native Windows application without Docker or WSL. It
                          is being rewritten and ships in a later phase — shown
                          here so you know it&#39;s planned, but it can&#39;t be
                          chosen yet.
                        </p>
                      </div>
                    )}
                  </div>
                  <span className="best">
                    <b>Best for:</b> one shared family computer, or trying
                    ApiaryLens out.
                  </span>
                </div>
                {availableTargets(windowsClientEnabled)
                  .filter(
                    (definition) =>
                      definition.id !== "compose-local" &&
                      definition.id !== "windows-client",
                  )
                  .map((definition) => (
                    <button
                      className={
                        "choice" + (target === definition.id ? " selected" : "")
                      }
                      role="radio"
                      aria-checked={target === definition.id}
                      key={definition.id}
                      onClick={() => setTarget(definition.id)}
                    >
                      <span className="radio" aria-hidden="true"></span>
                      <h2>
                        {definition.title}{" "}
                        <span className="flag">{definition.flag}</span>
                      </h2>
                      <p>{definition.description}</p>
                      <span className="best">
                        <b>Best for:</b> {definition.bestFor}
                      </span>
                    </button>
                  ))}
              </div>
              {scoutUpdate && (
                <div className="update-note" role="note">
                  <span className="flag soon">Scout update</span>
                  <p>
                    Scout Bee {scoutUpdate.latestVersion} is available (you have{" "}
                    {scoutUpdate.currentVersion}). Scout never updates itself or
                    runs in the background — download it from the official
                    release page when you choose, and verify the SHA-256 before
                    running it
                    {scoutUpdate.assetSha256 ? (
                      <>
                        : <code>{scoutUpdate.assetSha256}</code>
                      </>
                    ) : (
                      " against the release's SHA256SUMS file."
                    )}
                  </p>
                  {scoutUpdate.releaseUrl && (
                    <a
                      className="btn"
                      href={scoutUpdate.releaseUrl}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Open release page
                    </a>
                  )}
                </div>
              )}
              <details className="adv">
                <summary>Advanced release channel</summary>
                <div className="adv-body">
                  {(
                    [
                      [
                        "stable",
                        "Stable",
                        "recommended and selected by default. The newest release that has finished testing.",
                      ],
                      [
                        "preview",
                        "Preview",
                        "early builds for people helping test. Changing frequently — not for your family's only copy of the records.",
                      ],
                      [
                        "release-candidate",
                        "Release candidate",
                        "the final check before a stable release.",
                      ],
                    ] as const
                  ).map(([value, label, explanation]) => (
                    <label key={value}>
                      <input
                        type="radio"
                        name="chan"
                        checked={productChannel === value}
                        onChange={() => setProductChannel(value)}
                      />
                      <span>
                        <b>{label}</b> — {explanation}
                      </span>
                    </label>
                  ))}
                  <small>
                    Preview and RC builds require this explicit advanced
                    selection on every Scout installation.
                  </small>
                </div>
              </details>
              <section
                className="maintenance"
                aria-labelledby="recovery-status-heading"
              >
                <h3 id="recovery-status-heading" className="section-label">
                  On this computer
                </h3>
                <div className="status-strip">
                  <span>
                    <b>Last verified backup:</b>{" "}
                    {lastVerifiedBackup?.finishedAt
                      ? new Date(lastVerifiedBackup.finishedAt).toLocaleString()
                      : "none recorded"}
                  </span>
                  <span>
                    <b>Last restore:</b>{" "}
                    {lastRestore
                      ? `${lastRestore.status} · ${new Date(lastRestore.finishedAt ?? lastRestore.startedAt).toLocaleString()}`
                      : "none recorded"}
                  </span>
                </div>
                <div className="callout backup">
                  <h3>Backups — your safety net</h3>
                  <p>
                    A browser or phone’s offline working copy is not a server
                    backup. Scout backups include the deployment’s records and
                    private media, and Scout verifies every backup file after
                    writing it.
                  </p>
                  <div className="act">
                    <button className="btn" onClick={startBackup}>
                      Back up now
                    </button>
                  </div>
                </div>
              </section>
            </>
          )}
          {step === 2 && (
            <>
              <h1>Tell Scout Bee where to work.</h1>
              <section className="form">
                <label>
                  What should Scout Bee do?
                  <select
                    value={operation}
                    onChange={(event) => {
                      setOperation(event.target.value as Operation);
                      setRestoreAcknowledged(false);
                    }}
                  >
                    <option value="install">Install a new deployment</option>
                    <option value="update">
                      Update an existing deployment
                    </option>
                    <option value="repair">
                      Repair using the same verified release
                    </option>
                    <option value="rollback">
                      Roll back to a selected compatible release
                    </option>
                    <option value="backup">Create and verify a backup</option>
                    <option value="restore">Restore a verified backup</option>
                    <option
                      value="export"
                      disabled={target === "windows-client"}
                    >
                      Export owned data
                    </option>
                    <option value="uninstall">Uninstall ApiaryLens</option>
                  </select>
                </label>
                <div className="release-selection">
                  <b>Product release</b>
                  <span>
                    {release
                      ? `ApiaryLens ${release.version} · ${release.channel}`
                      : stableChannelEmpty && productChannel === "stable"
                        ? "ApiaryLens hasn’t shipped a stable release yet — previews are currently the only channel."
                        : "Resolving the official release identity…"}
                  </span>
                  {stableChannelEmpty && productChannel === "stable" ? (
                    <div className="act">
                      <button
                        className="btn"
                        onClick={() => setProductChannel("preview")}
                      >
                        Use the Preview channel
                      </button>
                    </div>
                  ) : (
                    <small>
                      Stable is always selected by default; the Advanced release
                      channel choice lives on the first screen.
                    </small>
                  )}
                </div>
                {target !== "windows-client" && target !== "compose-local" && (
                  <div
                    className="frontend-selection"
                    role="group"
                    aria-labelledby="frontend-selection-label"
                  >
                    <b id="frontend-selection-label">Deployment content</b>
                    <label>
                      <input
                        type="checkbox"
                        checked={includeWebFrontend}
                        onChange={(event) =>
                          setIncludeWebFrontend(event.target.checked)
                        }
                      />
                      Include the ApiaryLens web application
                    </label>
                    <small>
                      Clear this for a backend-only deployment used by connected
                      Windows or mobile clients. API, authentication, sync,
                      media, health checks, HTTPS, backup, and recovery remain
                      enabled.
                    </small>
                  </div>
                )}
                {target === "compose-local" ? (
                  <>
                    <div className="target-note" role="note">
                      <b>Local trial on this computer</b>
                      <p>
                        Scout runs the released ApiaryLens package here through
                        WSL2 with Docker on Windows (Docker Desktop), or Docker
                        on Linux. Everything stays on this machine at
                        http://localhost. Preflight checks that Docker is ready
                        and tells you what to install if it isn&#39;t. The
                        install folder defaults to ~/apiarylens inside your home
                        folder, which needs no administrator rights.
                      </p>
                    </div>
                    <label>
                      Install folder (inside WSL on Windows)
                      <input
                        required
                        name="localDirectory"
                        value={form.localDirectory}
                        onChange={(event) => {
                          update("localDirectory", event.target.value);
                          setLocalFolderState("");
                        }}
                        onBlur={() => void checkLocalFolder()}
                      />
                      {localFolderState === "unwritable" && (
                        <span className="field-hint" role="status">
                          This folder isn&#39;t writable here — try ~/apiarylens
                          (your home folder).
                        </span>
                      )}
                      {localFolderState === "writable" && (
                        <span className="field-ok" role="status">
                          This folder is ready to use.
                        </span>
                      )}
                    </label>
                    <Field
                      label="Project name"
                      name="projectName"
                      value={form.projectName}
                      update={update}
                    />
                    <Field
                      label="Local port"
                      name="localHttpPort"
                      value={form.localHttpPort}
                      update={update}
                      placeholder="8420"
                    />
                  </>
                ) : target === "compose-ssh" ? (
                  <>
                    <Field
                      label="Server address"
                      name="host"
                      value={form.host}
                      update={update}
                    />
                    <Field
                      label="Linux user"
                      name="user"
                      value={form.user}
                      update={update}
                    />
                    <Field
                      label="Install folder"
                      name="targetDirectory"
                      value={form.targetDirectory}
                      update={update}
                    />
                    <Field
                      label="Public HTTPS address"
                      name="publicUrl"
                      value={form.publicUrl}
                      update={update}
                    />
                    <Field
                      label="Verified SSH host key"
                      name="sshHostKeySha256"
                      value={form.sshHostKeySha256}
                      update={update}
                    />
                    <div className="ssh-authentication">
                      <label>
                        SSH authentication
                        <select
                          value={sshAuthMethod}
                          onChange={(event) => {
                            setSSHAuthMethod(
                              event.target.value as SSHAuthMethod,
                            );
                            setSSHPrivateKeyPath("");
                            setSSHPrivateKeyPassphrase("");
                            setSSHPassword("");
                          }}
                        >
                          <option value="agent">
                            OpenSSH agent or default identity
                          </option>
                          <option value="private-key">
                            Explicit private key file
                          </option>
                          <option value="password">
                            Password (Windows Scout only)
                          </option>
                        </select>
                      </label>
                      {sshAuthMethod === "private-key" && (
                        <>
                          <label className="runtime-secret">
                            Private key file
                            <input
                              type="text"
                              autoComplete="off"
                              value={sshPrivateKeyPath}
                              onChange={(event) =>
                                setSSHPrivateKeyPath(event.target.value)
                              }
                              placeholder="C:\\Users\\you\\.ssh\\id_ed25519"
                            />
                            <small>
                              The absolute path is used only for this operation.
                              It is never added to the plan, history, logs, or
                              diagnostics.
                            </small>
                          </label>
                          <label className="runtime-secret">
                            Private key passphrase (optional; Windows Scout
                            only)
                            <input
                              type="password"
                              autoComplete="off"
                              value={sshPrivateKeyPassphrase}
                              onChange={(event) =>
                                setSSHPrivateKeyPassphrase(event.target.value)
                              }
                              placeholder="Leave empty for an unencrypted key"
                            />
                            <small>
                              On Windows, Scout provides this through a
                              protected, temporary OpenSSH askpass boundary and
                              deletes it when the operation ends.
                            </small>
                          </label>
                        </>
                      )}
                      {sshAuthMethod === "password" && (
                        <label className="runtime-secret">
                          SSH password
                          <input
                            type="password"
                            autoComplete="off"
                            value={sshPassword}
                            onChange={(event) =>
                              setSSHPassword(event.target.value)
                            }
                            placeholder="Used only during this operation"
                          />
                          <small>
                            On Windows, Scout provides this through a protected,
                            temporary OpenSSH askpass boundary and deletes it
                            when the operation ends.
                          </small>
                        </label>
                      )}
                      {sshAuthMethod === "agent" && (
                        <small>
                          Scout uses the current OpenSSH agent and default
                          identity files without prompting or persisting a
                          credential.
                        </small>
                      )}
                    </div>
                  </>
                ) : target === "windows-client" ? (
                  <>
                    <div className="target-note" role="note">
                      <b>Current-user Windows installation</b>
                      <p>
                        Scout verifies the exact product manifest, package
                        checksums, and Authenticode signer before lifecycle
                        work. Backup and restore use protected runtime-only
                        request/evidence files; the archive path is never added
                        to the plan, history, logs, or diagnostics. Advanced
                        Windows data export remains unavailable.
                      </p>
                    </div>
                    {(operation === "backup" || operation === "restore") && (
                      <Field
                        label={
                          operation === "backup"
                            ? "New Windows backup file (.albackup)"
                            : "Existing Windows backup file (.albackup)"
                        }
                        name="windowsArchivePath"
                        value={form.windowsArchivePath}
                        update={update}
                        placeholder="C:\\Users\\you\\Documents\\apiarylens-family.albackup"
                      />
                    )}
                  </>
                ) : (
                  <>
                    <Field
                      label="Cloudflare account ID"
                      name="accountReference"
                      value={form.accountReference}
                      update={update}
                    />
                    <Field
                      label="ApiaryLens deployment name"
                      name="workerName"
                      value={form.workerName}
                      update={update}
                    />
                    <Field
                      label="Records database name"
                      name="d1DatabaseName"
                      value={form.d1DatabaseName}
                      update={update}
                    />
                    <Field
                      label="Private photo storage name"
                      name="r2BucketName"
                      value={form.r2BucketName}
                      update={update}
                    />
                    <Field
                      label="Deployment HTTPS address"
                      name="customDomain"
                      value={form.customDomain}
                      update={update}
                      placeholder="https://hives.example.com"
                    />
                    {(operation === "backup" ||
                      operation === "export" ||
                      operation === "update" ||
                      operation === "repair" ||
                      operation === "rollback") && (
                      <Field
                        label={
                          operation === "update" ||
                          operation === "repair" ||
                          operation === "rollback"
                            ? "Local folder for the required pre-update backup (optional)"
                            : "Local folder for the archive (optional)"
                        }
                        name="backupDestination"
                        value={form.backupDestination}
                        update={update}
                        placeholder="Defaults to your Downloads folder"
                      />
                    )}
                    {operation === "restore" && (
                      <Field
                        label="Verified backup file to restore"
                        name="backupFilePath"
                        value={form.backupFilePath}
                        update={update}
                        placeholder="C:\\Backups\\apiarylens-backup.zip"
                      />
                    )}
                  </>
                )}
              </section>
            </>
          )}
          {step === 3 && (
            <>
              <h1>Review before anything changes.</h1>
              <div className="review">
                <div>
                  <b>Release</b>
                  <span>
                    {release
                      ? `ApiaryLens ${release.version} · ${release.channel}`
                      : "Loading…"}
                  </span>
                </div>
                <div>
                  <b>Target</b>
                  <span>
                    {target === "compose-ssh"
                      ? "Your Linux server"
                      : target === "compose-local"
                        ? `This computer only — http://localhost:${Number.parseInt(form.localHttpPort, 10) || 8420}`
                        : target === "windows-client"
                          ? "This Windows account"
                          : target === "plan-only"
                            ? "Export only"
                            : "Your Cloudflare account"}
                  </span>
                </div>
                <div>
                  <b>Operation</b>
                  <span>{operation}</span>
                </div>
                {target !== "windows-client" && target !== "compose-local" && (
                  <div>
                    <b>Deployment content</b>
                    <span>
                      {includeWebFrontend
                        ? "Backend and web application"
                        : "Backend only"}
                    </span>
                  </div>
                )}
                {target === "compose-ssh" && (
                  <div>
                    <b>SSH authentication</b>
                    <span>
                      {sshAuthMethod === "agent"
                        ? "OpenSSH agent/default identity"
                        : sshAuthMethod === "private-key"
                          ? "Runtime-only private key"
                          : "Runtime-only password"}
                    </span>
                  </div>
                )}
                <div>
                  <b>Safety</b>
                  <span>
                    {target === "windows-client"
                      ? "Package identity, checksums, Authenticode signer, installed host security, and health are verified before completion."
                      : "SHA-256 checksums, the GitHub build attestation, HTTPS, authentication, backup readiness, and versions are verified before completion."}
                  </span>
                </div>
                {release && (
                  <div>
                    <b>Pinned manifest</b>
                    <span className="mono digest">
                      SHA-256 {release.manifestSha256}
                    </span>
                  </div>
                )}
              </div>
              {target === "cloudflare" && (
                <>
                  <CloudflareCostGuide />
                  <label className="cost-acknowledgement">
                    <input
                      type="checkbox"
                      checked={costAcknowledged}
                      onChange={(event) =>
                        setCostAcknowledged(event.target.checked)
                      }
                    />
                    I reviewed these dated allowances and understand that
                    Cloudflare can change pricing or limits.
                  </label>
                  <label className="runtime-secret">
                    Cloudflare API token
                    <input
                      type="password"
                      autoComplete="off"
                      value={cloudflareToken}
                      onChange={(event) =>
                        setCloudflareToken(event.target.value)
                      }
                      placeholder="Used only while this application is open"
                    />
                    <small>
                      This value stays in memory and is never added to the plan
                      or diagnostics.
                    </small>
                  </label>
                </>
              )}
              {ownerCodeNeeded && (
                <div
                  className="callout owner-code"
                  role="group"
                  aria-labelledby="owner-code-heading"
                >
                  <h3 id="owner-code-heading">Owner setup code</h3>
                  <p>
                    This code protects who gets to become the first owner
                    account on your ApiaryLens — you enter it once when creating
                    that account. It stays in memory here and is never added to
                    the plan or diagnostics.
                  </p>
                  {ownerCodeMode === "auto" ? (
                    target === "compose-local" ? (
                      <p className="owner-code-note">
                        Scout generated a strong random code for you — nothing
                        to type. It will be shown on the Finish screen; keep it
                        in case you ever reconnect this trial.
                      </p>
                    ) : (
                      <>
                        <div className="owner-code-value">
                          <code>{generatedOwnerCode}</code>
                          <button
                            type="button"
                            className="btn"
                            onClick={copyOwnerCode}
                          >
                            {ownerCodeCopied ? "Copied" : "Copy code"}
                          </button>
                        </div>
                        <label className="cost-acknowledgement">
                          <input
                            type="checkbox"
                            checked={ownerCodeSaved}
                            onChange={(event) =>
                              setOwnerCodeSaved(event.target.checked)
                            }
                          />
                          I copied and saved this code — I’ll need it to create
                          the first family owner.
                        </label>
                      </>
                    )
                  ) : (
                    <label className="runtime-secret">
                      My own setup code
                      <input
                        type="password"
                        autoComplete="new-password"
                        minLength={16}
                        required
                        aria-required="true"
                        aria-invalid={bootstrapToken.length < 16}
                        value={bootstrapToken}
                        onChange={(event) =>
                          setBootstrapToken(event.target.value)
                        }
                        placeholder="At least 16 characters; save it until setup is complete"
                      />
                      {bootstrapToken.length < 16 && (
                        <span className="field-hint" role="status">
                          Enter at least 16 characters, or switch back to the
                          generated code below.
                        </span>
                      )}
                    </label>
                  )}
                  <details className="adv">
                    <summary>Advanced: choose the code yourself</summary>
                    <div className="adv-body">
                      <label>
                        <input
                          type="radio"
                          name="owner-code-mode"
                          checked={ownerCodeMode === "auto"}
                          onChange={() => setOwnerCodeMode("auto")}
                        />
                        <span>
                          <b>Generated by Scout</b> — recommended; a strong
                          random code.
                        </span>
                      </label>
                      <label>
                        <input
                          type="radio"
                          name="owner-code-mode"
                          checked={ownerCodeMode === "custom"}
                          onChange={() => setOwnerCodeMode("custom")}
                        />
                        <span>
                          <b>Set my own</b> — at least 16 characters.
                        </span>
                      </label>
                    </div>
                  </details>
                </div>
              )}
              {operation === "uninstall" && (
                <label className="keep-data">
                  <input
                    type="checkbox"
                    checked={keepData}
                    onChange={(event) => setKeepData(event.target.checked)}
                  />
                  Keep database and media volumes so the deployment can be
                  recovered later
                </label>
              )}
              {operation === "restore" && (
                <div className="restore-warning" role="note">
                  <strong>
                    Restore replaces current{" "}
                    {target === "windows-client" ? "Windows" : "server"} records
                    and media.
                  </strong>
                  <p>
                    Scout first creates a recovery backup, verifies the selected
                    archive and target compatibility, restores the{" "}
                    {target === "windows-client" ? "Windows data" : "server"},
                    revokes existing sign-in sessions, and requires a passing
                    health check.
                  </p>
                  <label>
                    <input
                      type="checkbox"
                      checked={restoreAcknowledged}
                      onChange={(event) =>
                        setRestoreAcknowledged(event.target.checked)
                      }
                    />
                    I understand the current server data will be replaced and
                    users must sign in again.
                  </label>
                </div>
              )}
              <details className="plan-details">
                <summary>View the operator plan</summary>
                <pre>{JSON.stringify(plan, null, 2)}</pre>
              </details>
            </>
          )}
          {step === 4 && (
            <>
              <h1>
                {lastRunMode === "dry-run"
                  ? "Preflight checks — nothing was changed"
                  : runFailed
                    ? "Scout Bee stopped safely."
                    : `${operationHeadline(operation)} — every check shown`}
              </h1>
              {release && (
                <p className="lede">
                  Requested release: <b>ApiaryLens {release.version}</b> ·{" "}
                  {release.channel}. Scout checks every download against the
                  pinned release record before anything is installed.
                </p>
              )}
              <div className="steps">
                {phases.map((phase) => (
                  <div
                    className={
                      "step-row" + (phase.state === "waiting" ? " dim" : "")
                    }
                    key={phase.name}
                  >
                    <span className="mark">
                      {phase.state === "passed" ? (
                        <span className="check" aria-hidden="true">
                          ✓
                        </span>
                      ) : phase.state === "failed" ? (
                        <span className="cross" aria-hidden="true">
                          ✕
                        </span>
                      ) : (
                        <span className="idle" aria-hidden="true"></span>
                      )}
                    </span>
                    <div>
                      <h3>
                        {phase.name}{" "}
                        <span
                          className={
                            "state " +
                            (phase.state === "passed"
                              ? "ok"
                              : phase.state === "failed"
                                ? "bad"
                                : "wait")
                          }
                        >
                          {phase.state === "passed"
                            ? "Done"
                            : phase.state === "failed"
                              ? "Failed"
                              : phase.state}
                        </span>
                      </h3>
                      {phase.detail && <p>{phase.detail}</p>}
                    </div>
                  </div>
                ))}
              </div>
              {release && (
                <div className="evidence">
                  <div className="row">
                    <span className="ok-word">Pinned release manifest</span>
                    SHA-256:
                  </div>
                  <div className="row">
                    <code>{release.manifestSha256}</code>
                  </div>
                  <div className="row muted-row">
                    If any check had failed, Scout would have stopped there and
                    told you. No secret values were written to the plan or log.
                  </div>
                </div>
              )}
              <div className="progress-actions">
                {phases.some(
                  (phase) =>
                    phase.state === "failed" &&
                    (phase.detail ?? "").includes("owner setup code"),
                ) && (
                  <button className="btn primary" onClick={() => setStep(3)}>
                    Go to Review and enter the code
                  </button>
                )}
                {runFailed &&
                  (lastRunMode === "apply" || lastRunMode === "resume") && (
                    <button className="btn" onClick={() => void run("resume")}>
                      Resume safely
                    </button>
                  )}
                <button className="btn" onClick={() => void saveDiagnostics()}>
                  Save sanitized diagnostics
                </button>
              </div>
            </>
          )}
          {step === 5 && (
            <>
              <div className="done-hero">
                <span className="big-check" aria-hidden="true">
                  ✓
                </span>
                <div>
                  <h1>
                    {operation === "install"
                      ? "All set — ApiaryLens is ready"
                      : operation === "backup"
                        ? "Backup created and verified"
                        : "The requested work completed"}
                  </h1>
                  {release && healthVerified && (
                    <div className="health-line">
                      <span className="state ok">Verified</span>
                      The deployment reports exactly release{" "}
                      <b>{release.version}</b> — what was requested is what is
                      running.
                    </div>
                  )}
                </div>
              </div>
              {backendAddress && (
                <div className="callout">
                  <h3>Open ApiaryLens</h3>
                  <p>
                    Start keeping records — hives, inspections, harvests. Your
                    family signs in at this address.
                  </p>
                  <div className="act">
                    <a
                      className="btn primary"
                      href={backendAddress}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Open ApiaryLens
                    </a>
                    <code>{backendAddress}</code>
                  </div>
                </div>
              )}
              {operation === "install" &&
                target === "compose-local" &&
                ownerCodeMode === "auto" && (
                  <div className="callout">
                    <h3>Your owner setup code (saved)</h3>
                    <p>
                      ApiaryLens will ask for it once when you create the first
                      family owner account. Keep it somewhere safe in case you
                      ever reconnect this trial.
                    </p>
                    <div className="owner-code-value">
                      <code>{generatedOwnerCode}</code>
                      <button
                        type="button"
                        className="btn"
                        onClick={copyOwnerCode}
                      >
                        {ownerCodeCopied ? "Copied" : "Copy code"}
                      </button>
                    </div>
                  </div>
                )}
              {operation !== "backup" && (
                <div className="callout backup">
                  <h3>
                    {lastVerifiedBackup
                      ? "Keep your backups current"
                      : "Make your first backup"}
                  </h3>
                  <p>
                    A backup file kept somewhere else — a USB stick, another
                    computer — is what protects your family’s records if this
                    deployment fails. Scout verifies every backup file after
                    writing it.
                  </p>
                  <div className="act">
                    <button className="btn primary" onClick={startBackup}>
                      Back up now
                    </button>
                  </div>
                </div>
              )}
              {connectionProfile ? (
                <div className="callout">
                  <h3>Connection file for other devices</h3>
                  <p>
                    The verified deployment is ready to connect the ApiaryLens
                    apps on the family’s other devices. The connection file
                    contains no credentials.
                  </p>
                  <div className="act">
                    <button className="btn" onClick={saveConnectionProfile}>
                      Save connection file
                    </button>
                  </div>
                </div>
              ) : (
                <div className="callout muted">
                  <h3>No connection profile for this setup</h3>
                  <p>
                    {target === "compose-local"
                      ? "With everything on one computer there is nothing to connect, so Scout didn’t write one. Cloud and own-server setups get a secret-free connection file here to hand to the family’s other devices."
                      : "Nothing here needs connecting, so Scout didn’t write one. Cloud and own-server installs get a secret-free connection file here to hand to the family’s other devices."}
                  </p>
                </div>
              )}
              <p className="lede close-note">
                You can close Scout now — nothing keeps running in the
                background. Open Scout again whenever you want to update, back
                up, restore, or repair.
              </p>
            </>
          )}
        </div>
        <div className="footerbar">
          {step === 1 && (
            <span className="hint">
              Nothing is downloaded or installed until you review the summary
              and choose to apply it.
            </span>
          )}
          {step === 3 && (
            <button className="btn quiet" onClick={exportPlan}>
              Export plan
            </button>
          )}
          {step === 4 && (
            <button
              className="btn quiet"
              onClick={() => void saveDiagnostics()}
            >
              Diagnostics
            </button>
          )}
          {step === 5 && (
            <span className="hint">
              Operation history saved — no passwords or secrets in it.
            </span>
          )}
          <span className="grow"></span>
          {busy && (
            <button className="btn danger" onClick={() => void cancel()}>
              Cancel safely
            </button>
          )}
          {step > 1 && step < 5 && (
            <button
              className="btn"
              disabled={busy}
              onClick={() => setStep(step - 1)}
            >
              Back
            </button>
          )}
          {step === 1 && (
            <button className="btn primary" onClick={() => setStep(2)}>
              Next
            </button>
          )}
          {step === 2 && (
            <button className="btn primary" onClick={() => setStep(3)}>
              Next
            </button>
          )}
          {step === 3 && (
            <>
              {ownerCodeMissing && (
                <span className="hint">
                  {ownerCodeMode === "custom"
                    ? "Enter a setup code of at least 16 characters above to continue."
                    : "Confirm you saved the owner setup code above to continue."}
                </span>
              )}
              <button
                className="btn"
                disabled={
                  busy ||
                  !release ||
                  ownerCodeMissing ||
                  (target === "cloudflare" && !costAcknowledged)
                }
                onClick={() => void run("dry-run")}
              >
                {busy ? "Checking…" : "Run preflight"}
              </button>
              {target !== "plan-only" && (
                <button
                  className="btn primary"
                  disabled={
                    busy ||
                    !release ||
                    ownerCodeMissing ||
                    (target === "cloudflare" && !costAcknowledged) ||
                    (target === "cloudflare" && cloudflareToken.length === 0) ||
                    (operation === "restore" && !restoreAcknowledged) ||
                    (operation === "restore" &&
                      target === "cloudflare" &&
                      form.backupFilePath.length === 0) ||
                    (target === "compose-ssh" &&
                      sshAuthMethod === "private-key" &&
                      sshPrivateKeyPath.length === 0) ||
                    (target === "compose-ssh" &&
                      sshAuthMethod === "password" &&
                      sshPassword.length === 0) ||
                    ((operation === "backup" || operation === "restore") &&
                      target === "windows-client" &&
                      form.windowsArchivePath.length === 0)
                  }
                  onClick={() => void run("apply")}
                >
                  Apply{" "}
                  {target === "windows-client"
                    ? "Windows lifecycle"
                    : "deployment"}
                </button>
              )}
            </>
          )}
          {step === 4 && (
            <button
              className="btn primary"
              disabled={busy || !applyPassed}
              onClick={() => setStep(5)}
            >
              Next
            </button>
          )}
          {step === 5 && (
            <button className="btn primary" onClick={finishWizard}>
              Finish
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
function operationHeadline(operation: Operation) {
  switch (operation) {
    case "install":
      return "Setting up ApiaryLens";
    case "update":
      return "Updating ApiaryLens";
    case "repair":
      return "Repairing this install";
    case "rollback":
      return "Rolling back ApiaryLens";
    case "backup":
      return "Creating a verified backup";
    case "restore":
      return "Restoring a verified backup";
    case "export":
      return "Exporting owned data";
    default:
      return "Removing ApiaryLens";
  }
}
function CloudflareCostGuide() {
  return (
    <aside className="cost-guide" aria-labelledby="cloudflare-cost-heading">
      <div>
        <p className="eyebrow">Guarded family cost profile</p>
        <h2 id="cloudflare-cost-heading">
          Cloudflare Free allowances checked July 15, 2026
        </h2>
        <p>
          Scout Bee does not enable a paid plan. A modest family deployment is
          expected to fit within these allowances, but actual use and provider
          terms determine the bill.
        </p>
      </div>
      <dl>
        {cloudflareAllowances.map(([service, allowance]) => (
          <div key={service}>
            <dt>{service}</dt>
            <dd>{allowance}</dd>
          </div>
        ))}
      </dl>
      <p className="cost-note">
        Static Worker assets and R2 internet egress are currently free. Domain
        registration, backups outside this account, optional paid plans, and
        internet access are separate. Free-limit exhaustion can stop requests
        instead of producing a permanent-free guarantee.
      </p>
    </aside>
  );
}
function Field({
  label,
  name,
  value,
  update,
  placeholder,
}: {
  label: string;
  name: string;
  value: string;
  update: (n: string, v: string) => void;
  placeholder?: string;
}) {
  return (
    <label>
      {label}
      <input
        required
        name={name}
        value={value}
        placeholder={placeholder}
        onChange={(event) => update(name, event.target.value)}
      />
    </label>
  );
}
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
